#!/usr/bin/env bash
# Fix Ubuntu Container's to listen on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites/sites-enabled/default
service nginx restart
